  service: todo-api
  provider:
    name: aws
    runtime: nodejs18.x
    region: eu-west-1
    environment:
      TODOS_TABLE: ${env:TODOS_TABLE}
  resources:
    Resources:
      LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service: lambda.amazonaws.com
                Action: sts:AssumeRole
          Policies:
            - PolicyName: LambdaDynamoDBPolicy
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:PutItem
                      - dynamodb:Query
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                    Resource:
                      - arn:aws:dynamodb:${self:provider.region}:*:table/${env:TODOS_TABLE}
                      - arn:aws:dynamodb:${self:provider.region}:*:table/${env:TODOS_TABLE}/index/*
      TodosTable:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          TableName: ${env:TODOS_TABLE}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
            - AttributeName: status
              AttributeType: S
            - AttributeName: dueDate
              AttributeType: S
            - AttributeName: createdTime
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
          GlobalSecondaryIndexes:
            - IndexName: StatusIndex
              KeySchema:
                - AttributeName: status
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
            - IndexName: DueDateIndex
              KeySchema:
                - AttributeName: dueDate
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
            - IndexName: CreatedTimeIndex
              KeySchema:
                - AttributeName: createdTime
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
  functions:
    createTodo:
      handler: src/handlers/createTodo.handler
      events:
        - http:
            path: todos
            method: post
      role: LambdaExecutionRole

    getTodos:
      handler: src/handlers/filterTodo.handler
      events:
        - http:
            path: todos
            method: get
            request:
              parameters:
                querystrings:
                  status: false
                  createdTime: false
                  dueDate: false
      role: LambdaExecutionRole
    updateTodo:
      handler: src/handlers/updateTodo.handler
      events:
        - http:
            path: todos/{id}
            method: put
      role: LambdaExecutionRole

    deleteTodo:
      handler: src/handlers/deleteTodo.handler
      events:
        - http:
            path: todos/{id}
            method: delete
      role: LambdaExecutionRole
